data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_train_dir: train
  ingestd_test_dir: test

training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact
